#ifndef MAUS_INPUT_H
#define MAUS_INPUT_H

#include <stdint.h>

typedef enum {
	MAUS_KEY_NONE = 0,

	MAUS_KEY_TAB = '\t',     MAUS_KEY_ENTER = '\n',   MAUS_KEY_SPACE = ' ',
	MAUS_KEY_APOSTROPHE = '\'', MAUS_KEY_COMMA = ',',  MAUS_KEY_MINUS = '-',
	MAUS_KEY_PERIOD = '.',   MAUS_KEY_SLASH = '/',    MAUS_KEY_SEMICOLON = ';',
	MAUS_KEY_EQUAL = '=',    MAUS_KEY_LEFT_BRACKET = '[', MAUS_KEY_BACKSLASH = '\\',
	MAUS_KEY_RIGHT_BRACKET = ']', MAUS_KEY_GRAVE = '`',

	/* numbers */
	MAUS_KEY_0 = '0', MAUS_KEY_1, MAUS_KEY_2, MAUS_KEY_3, MAUS_KEY_4,
	MAUS_KEY_5,       MAUS_KEY_6, MAUS_KEY_7, MAUS_KEY_8, MAUS_KEY_9,

	/* uppercase */
	MAUS_KEY_A_UP = 'A', MAUS_KEY_B_UP, MAUS_KEY_C_UP, MAUS_KEY_D_UP, MAUS_KEY_E_UP,
	MAUS_KEY_F_UP,       MAUS_KEY_G_UP, MAUS_KEY_H_UP, MAUS_KEY_I_UP, MAUS_KEY_J_UP,
	MAUS_KEY_K_UP,       MAUS_KEY_L_UP, MAUS_KEY_M_UP, MAUS_KEY_N_UP, MAUS_KEY_O_UP,
	MAUS_KEY_P_UP,       MAUS_KEY_Q_UP, MAUS_KEY_R_UP, MAUS_KEY_S_UP, MAUS_KEY_T_UP,
	MAUS_KEY_U_UP,       MAUS_KEY_V_UP, MAUS_KEY_W_UP, MAUS_KEY_X_UP, MAUS_KEY_Y_UP,
	MAUS_KEY_Z_UP,

	/* lowercase */
	MAUS_KEY_A = 'a', MAUS_KEY_B, MAUS_KEY_C, MAUS_KEY_D, MAUS_KEY_E,
	MAUS_KEY_F,       MAUS_KEY_G, MAUS_KEY_H, MAUS_KEY_I, MAUS_KEY_J,
	MAUS_KEY_K,       MAUS_KEY_L, MAUS_KEY_M, MAUS_KEY_N, MAUS_KEY_O,
	MAUS_KEY_P,       MAUS_KEY_Q, MAUS_KEY_R, MAUS_KEY_S, MAUS_KEY_T,
	MAUS_KEY_U,       MAUS_KEY_V, MAUS_KEY_W, MAUS_KEY_X, MAUS_KEY_Y,
	MAUS_KEY_Z,

	MAUS_KEY_BACKSPACE = 128, MAUS_KEY_ESCAPE,      MAUS_KEY_DELETE,

	/* navigation */
	MAUS_KEY_LEFT,          MAUS_KEY_RIGHT,     MAUS_KEY_UP,        MAUS_KEY_DOWN,
	MAUS_KEY_HOME,          MAUS_KEY_END,       MAUS_KEY_PAGE_UP,   MAUS_KEY_PAGE_DOWN,
	MAUS_KEY_INSERT,

	/* modifiers */
	MAUS_KEY_SHIFT_L,       MAUS_KEY_SHIFT_R,   MAUS_KEY_CONTROL_L, MAUS_KEY_CONTROL_R,
	MAUS_KEY_ALT_L,         MAUS_KEY_ALT_R,     MAUS_KEY_SUPER_L,   MAUS_KEY_SUPER_R,
	MAUS_KEY_CAPS_LOCK,     MAUS_KEY_NUM_LOCK,  MAUS_KEY_SCROLL_LOCK,

	/* function */
	MAUS_KEY_F1,            MAUS_KEY_F2,        MAUS_KEY_F3,        MAUS_KEY_F4,
	MAUS_KEY_F5,            MAUS_KEY_F6,        MAUS_KEY_F7,        MAUS_KEY_F8,
	MAUS_KEY_F9,            MAUS_KEY_F10,       MAUS_KEY_F11,       MAUS_KEY_F12,

	MAUS_KEY_PRINT_SCREEN,  MAUS_KEY_PAUSE,     MAUS_KEY_MENU,

	/* keypad */
	MAUS_KEY_KP_0,          MAUS_KEY_KP_1,      MAUS_KEY_KP_2,      MAUS_KEY_KP_3,
	MAUS_KEY_KP_4,          MAUS_KEY_KP_5,      MAUS_KEY_KP_6,      MAUS_KEY_KP_7,
	MAUS_KEY_KP_8,          MAUS_KEY_KP_9,

	MAUS_KEY_KP_DECIMAL,    MAUS_KEY_KP_DIVIDE, MAUS_KEY_KP_MULTIPLY,
	MAUS_KEY_KP_SUBTRACT,   MAUS_KEY_KP_ADD,    MAUS_KEY_KP_ENTER,  MAUS_KEY_KP_EQUAL,

	MAUS_KEY_LAST,
} MausKey;

typedef struct {
	int32_t        x;
	int32_t        y;
} MausCursor;

typedef enum {
	MAUS_CURSOR_STATE_VISIBLE,
	MAUS_CURSOR_STATE_HIDDEN,
	MAUS_CURSOR_STATE_LOCKED,
	MAUS_CURSOR_STATE_FREE,
} MausCursorState;

typedef enum {
	MAUS_MOUSE_BUTTON_NONE = 0,
	MAUS_MOUSE_BUTTON_LEFT,
	MAUS_MOUSE_BUTTON_MIDDLE,
	MAUS_MOUSE_BUTTON_RIGHT,
	MAUS_MOUSE_BUTTON_SCROLL_UP,
	MAUS_MOUSE_BUTTON_SCROLL_DOWN,
	MAUS_MOUSE_BUTTON_LAST,
} MausMouseButton;

#endif /* MAUS_KEYS_H */

